# Generated by Django 5.1.3 on 2024-11-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('usuario', 'Usuário'), ('anfitriao', 'Anfitrião')], default='usuario', max_length=10),
        ),
    ]
