# Generated by Django 5.1.3 on 2024-11-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localesportivo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localesportivo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
