# Generated by Django 5.1.3 on 2024-11-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0004_alter_localesportivo_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localesportivo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localesportivo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
