# Generated by Django 5.1.3 on 2024-11-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0006_remove_localesportivo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localesportivo',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
