# Generated by Django 5.1.3 on 2024-11-19 16:48

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('horario_inicio', models.TimeField(default=datetime.time(9, 0))),
                ('horario_fim', models.TimeField(default=datetime.time(10, 0))),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='local.localesportivo')),
            ],
        ),
    ]
